name: MainPlugin
version: '${project.version}'
main: server.main.Main
api-version: 1.19

commands:
   warp:
   lobby:
   start:
   invsee:
   skywars:
   bedwars:
   spawn:
   kit:
   tntrun:
   stickbattle:
